### ISSUE TITLE
unable to bring up ipop tunnels in container

### ISSUE THREAD

**Issue by saket424** [cstapler/ipop-scale-test#1]
Hi,
I tried to follow the procedures documented in your repository to try out the bleeding edge Tincan without success. Any ideas?

Here is the ctlr.log on one of the lxc-container nodes

root@node4:/home/ubuntu/ipop# cat ctlr.log
Exception caught in CFX: 'dependencies'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/ipop/controller/Controller.py", line 36, in <module>
    main()
  File "/home/ubuntu/ipop/controller/Controller.py", line 31, in main
    cfx.initialize()
  File "controller/framework/CFx.py", line 75, in initialize
    self.load_module(key)
  File "controller/framework/CFx.py", line 109, in load_module
    instance = module_class(handle, self.CONFIG[module_name], module_name)
  File "controller/modules/XmppClient.py", line 132, in __init__
    self.ipop_xmpp_details[interface_name]["uid"] = interface_details["uid"]
KeyError: 'uid'

Also ifconfig does not have the tun interface

root@node2:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:16:3e:d8:c8:ea  
          inet addr:10.0.3.18  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::216:3eff:fed8:c8ea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5104 (5.1 KB)  TX bytes:1374 (1.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

oot@node2:/home/ubuntu/ipop# ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Jul  3 18:51 /dev/net/tun

**Comment by cstapler** [comment]
Hi @saket424,
This issue was caused mostly likely from a difference between the configuration file I supply and the configuration that the Controller required at that point in time. The latest code on this repo should be able to run testing with group-vpn mode for master branches of the Controllers and TIncan repos on an Ubuntu 16.04 machine. 

Also, I have started to develop this codebase on https://github.com/ipop-project/Release-Management. Scale test can be found under the Test directory. 

https://github.com/ipop-project/ipop-project.github.io/wiki/Introduction-to-the-scale-test-script-usage is where we will keep an up to date guide on how to use the scale test.

 Thanks!
